# Generated by Django 4.0.3 on 2024-05-07 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_securitydisplaythreshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='securityDisplayThreshold',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='security_display_threshold',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Minimum Teilnehmende für die Datenaggregation'),
        ),
    ]
