# Generated by Django 4.0.3 on 2024-05-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_securitydisplaythreshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='security_display_threshold',
        ),
    ]
