# Generated by Django 4.0.3 on 2024-09-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userprofile_security_display_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=True, verbose_name='Passwort ändern erforderlich'),
        ),
    ]
