# Generated by Django 4.0.3 on 2023-10-20 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_profiles', '0007_jobprofile_show_job_profile'),
        ('threats', '0008_alter_threatsituation_threat_vector'),
        ('competence_tests', '0012_chatinterface_chat_sender_known'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenceDimensionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoredPoints', models.IntegerField()),
                ('competence_dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competence_tests.competencedimension')),
            ],
        ),
        migrations.CreateModel(
            name='ThreatSituationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoredPoints', models.IntegerField()),
                ('threat_situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threats.threatsituation')),
                ('threat_vector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threats.threatvector')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_participated', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompetenceTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence_dimension_score', models.ManyToManyField(to='campagne.competencedimensionscore')),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_profiles.jobprofile')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campagne.invitation')),
                ('threat_situation_score', models.ManyToManyField(to='campagne.threatsituationscore')),
            ],
        ),
    ]
