# Generated by Django 4.0.3 on 2023-11-28 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campagne', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competencetestresult',
            name='participant',
        ),
        migrations.AddField(
            model_name='competencetestresult',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
