# Generated by Django 4.0.3 on 2024-01-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0002_remove_competencetestresult_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='one_token_mode',
            field=models.BooleanField(null=True),
        ),
    ]
