# Generated by Django 4.0.3 on 2024-01-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0004_remove_invitation_one_token_mode_campagne'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='reusable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitation',
            name='tokenCounter',
            field=models.IntegerField(null=True),
        ),
    ]
