# Generated by Django 4.0.3 on 2024-01-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0005_invitation_reusable_invitation_tokencounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='tokenCounter',
            field=models.IntegerField(default=0),
        ),
    ]
