# Generated by Django 4.0.3 on 2024-01-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0006_alter_invitation_tokencounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='email_encrypted',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
