# Generated by Django 4.0.3 on 2024-01-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0008_invitation_invited'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='reminded',
            field=models.BooleanField(default=False),
        ),
    ]
