# Generated by Django 4.0.3 on 2024-02-01 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0009_invitation_reminded'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatsituationscore',
            name='competence_dimension_score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campagne.competencedimensionscore'),
        ),
    ]
