# Generated by Django 4.0.3 on 2024-02-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0010_threatsituationscore_competence_dimension_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threatsituationscore',
            name='competence_dimension_score',
        ),
        migrations.AddField(
            model_name='threatsituationscore',
            name='competence_dimension_score',
            field=models.ManyToManyField(to='campagne.competencedimensionscore'),
        ),
    ]
