# Generated by Django 4.0.3 on 2024-02-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0012_competencedimensionscoreperthreat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threatsituationscore',
            old_name='competence_dimension_score',
            new_name='related_competence_dimension_scores',
        ),
    ]
