# Generated by Django 4.0.3 on 2024-03-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0013_rename_competence_dimension_score_threatsituationscore_related_competence_dimension_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='security_key_activated',
            field=models.BooleanField(default=True),
        ),
    ]
