# Generated by Django 4.0.3 on 2024-05-11 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0014_campagne_security_key_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='security_display_profile',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='campagne',
            name='security_display_threshold',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Minimum Teilnehmende für die Datenaggregation'),
        ),
    ]
