# Generated by Django 4.0.3 on 2024-05-12 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0015_campagne_security_display_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='campaign_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='security_display_threshold',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimum Teilnehmende für die Datenaggregation'),
        ),
    ]
