# Generated by Django 4.0.3 on 2024-05-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0016_campagne_campaign_ended_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campagne',
            name='security_display_profile',
        ),
        migrations.AddField(
            model_name='campagne',
            name='aggregate_over_single_profiles',
            field=models.BooleanField(default=True),
        ),
    ]
