# Generated by Django 4.0.3 on 2022-06-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence_tests', '0002_alter_chatimpulse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatinterface',
            name='chat_message_incoming_date_2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
