# Generated by Django 4.0.3 on 2022-06-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence_tests', '0003_alter_chatinterface_chat_message_incoming_date_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatimpulse',
            name='chat_interface',
        ),
        migrations.AddField(
            model_name='chatimpulse',
            name='chat_interface',
            field=models.ManyToManyField(to='competence_tests.chatinterface'),
        ),
    ]
