# Generated by Django 4.0.3 on 2022-06-28 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0001_initial'),
        ('job_profiles', '0004_remove_jobprofile_job_category'),
        ('competence_tests', '0004_remove_chatimpulse_chat_interface_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatinterface',
            options={'verbose_name': 'Chat Interface', 'verbose_name_plural': 'Chat Interfaces'},
        ),
        migrations.AlterModelOptions(
            name='choiceitem',
            options={'verbose_name': 'Antwort', 'verbose_name_plural': 'Antworten'},
        ),
        migrations.AlterModelOptions(
            name='competencetest',
            options={'verbose_name': 'Kompetenztest', 'verbose_name_plural': 'Kompetenztests'},
        ),
        migrations.RemoveField(
            model_name='chatinterface',
            name='chat_recipient_name',
        ),
        migrations.AlterField(
            model_name='chatimpulse',
            name='chat_interface',
            field=models.ManyToManyField(to='competence_tests.chatinterface', verbose_name='Chat Interface'),
        ),
        migrations.AlterField(
            model_name='chatimpulse',
            name='impulse_text',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Text zum Impuls'),
        ),
        migrations.AlterField(
            model_name='chatinterface',
            name='chat_message_incoming',
            field=models.CharField(max_length=800, verbose_name='Eingehende Nachricht 1'),
        ),
        migrations.AlterField(
            model_name='chatinterface',
            name='chat_message_incoming_2',
            field=models.CharField(blank=True, max_length=800, verbose_name='Eingehende Nachricht 2 (optional)'),
        ),
        migrations.AlterField(
            model_name='chatinterface',
            name='chat_message_incoming_date',
            field=models.DateField(verbose_name='Datum der 1. eingehenden Nachricht'),
        ),
        migrations.AlterField(
            model_name='chatinterface',
            name='chat_message_incoming_date_2',
            field=models.DateField(blank=True, null=True, verbose_name='Datum der 2. eingehenden Nachricht (optional)'),
        ),
        migrations.AlterField(
            model_name='chatinterface',
            name='chat_message_outgoing',
            field=models.CharField(blank=True, max_length=800, verbose_name='Ausgehende Nachricht (optional)'),
        ),
        migrations.AlterField(
            model_name='chatinterface',
            name='chat_message_outgoing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum der ausgehenden Nachricht (optional)'),
        ),
        migrations.AlterField(
            model_name='chatinterface',
            name='chat_sender_image',
            field=models.ImageField(blank=True, upload_to='static/images', verbose_name='Bild des Senders'),
        ),
        migrations.AlterField(
            model_name='chatinterface',
            name='chat_sender_name',
            field=models.CharField(max_length=140, verbose_name='Name des Senders'),
        ),
        migrations.AlterField(
            model_name='choiceitem',
            name='answer_rating',
            field=models.IntegerField(choices=[(0, 'Am Schlechtesten'), (1, 'Mittel'), (2, 'Am Besten')], default=0, verbose_name='Bewertung der Antwortoption'),
        ),
        migrations.AlterField(
            model_name='choiceitem',
            name='option',
            field=models.CharField(max_length=800, verbose_name='Antwortoption'),
        ),
        migrations.AlterField(
            model_name='choiceitem',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionn', to='competence_tests.questionitem', verbose_name='Zugeordnete Frage'),
        ),
        migrations.AlterField(
            model_name='competencedimension',
            name='dimension_description',
            field=models.CharField(max_length=800, verbose_name='Beschreibung der Kompetenzdimension'),
        ),
        migrations.AlterField(
            model_name='competencetest',
            name='job_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job_profiles.jobprofile', verbose_name='Zugeordnetes Anforderungsprofil'),
        ),
        migrations.AlterField(
            model_name='competencetest',
            name='threat_vector',
            field=models.ManyToManyField(to='threats.threatvector', verbose_name='Zugeordnete Bedrohungsvektoren'),
        ),
        migrations.AlterField(
            model_name='competencetestitem',
            name='competence_dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competence_tests.competencedimension', verbose_name='Zugeordnete Kompetenzdimension'),
        ),
        migrations.AlterField(
            model_name='competencetestitem',
            name='impulse_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competence_tests.impulse', verbose_name='Zugeordneter Impuls'),
        ),
        migrations.AlterField(
            model_name='competencetestitem',
            name='question_item',
            field=models.ManyToManyField(blank=True, to='competence_tests.questionitem', verbose_name='Zugeordnete Frage'),
        ),
        migrations.AlterField(
            model_name='competencetestitem',
            name='threat_situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threats.threatsituation', verbose_name='Zugeordnete Bedrohungssituation'),
        ),
        migrations.AlterField(
            model_name='emailimpulse',
            name='email',
            field=models.ManyToManyField(to='competence_tests.emailitem', verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='emailimpulse',
            name='impulse_text',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Text zum Impuls'),
        ),
        migrations.AlterField(
            model_name='emailitem',
            name='email_button_text',
            field=models.CharField(blank=True, max_length=140, verbose_name='Text für Button'),
        ),
        migrations.AlterField(
            model_name='emailitem',
            name='email_content',
            field=models.CharField(max_length=800, null=True, verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='emailitem',
            name='email_date',
            field=models.DateField(verbose_name='Datum der E-Mail'),
        ),
        migrations.AlterField(
            model_name='emailitem',
            name='email_image_sender',
            field=models.ImageField(upload_to='static/images', verbose_name='Bild des Senders'),
        ),
        migrations.AlterField(
            model_name='emailitem',
            name='email_name',
            field=models.CharField(max_length=140, null=True, verbose_name='Name der E-Mail'),
        ),
        migrations.AlterField(
            model_name='emailitem',
            name='email_recipient',
            field=models.CharField(max_length=140, null=True, verbose_name='Empfänger der E-Mail'),
        ),
        migrations.AlterField(
            model_name='emailitem',
            name='email_regarding',
            field=models.CharField(max_length=140, null=True, verbose_name='Betreff'),
        ),
        migrations.AlterField(
            model_name='emailitem',
            name='email_sender',
            field=models.CharField(max_length=140, null=True, verbose_name='Sender der E-Mail'),
        ),
        migrations.AlterField(
            model_name='imageimpulse',
            name='image',
            field=models.ManyToManyField(to='competence_tests.imageitem', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='imageimpulse',
            name='impulse_text',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Text zum Impuls'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='image_description',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Beschreibung des Bildes'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='image_field',
            field=models.ImageField(upload_to='static/images', verbose_name='Bild-Datei'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='image_name',
            field=models.CharField(max_length=140, null=True, verbose_name='Name des Bildes'),
        ),
        migrations.AlterField(
            model_name='impulse',
            name='impulse_name',
            field=models.CharField(max_length=140, null=True, verbose_name='Name des Impulses'),
        ),
        migrations.AlterField(
            model_name='questionitem',
            name='question',
            field=models.CharField(max_length=800, verbose_name='Frage'),
        ),
        migrations.AlterField(
            model_name='questionitem',
            name='question_name',
            field=models.CharField(max_length=140, null=True, verbose_name='Name der Frage'),
        ),
        migrations.AlterField(
            model_name='questionitem',
            name='type',
            field=models.IntegerField(choices=[(1, 'Single Choice Item'), (2, 'Multiple Choice Item'), (3, 'Ranking Item')], default=1, verbose_name='Fragen-Typ'),
        ),
    ]
