# Generated by Django 4.0.3 on 2022-06-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence_tests', '0007_alter_choiceitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatinterface',
            name='chat_message_outgoing_date',
            field=models.TimeField(blank=True, null=True, verbose_name='Datum der ausgehenden Nachricht (optional)'),
        ),
        migrations.AlterField(
            model_name='emailitem',
            name='email_date',
            field=models.TimeField(verbose_name='Datum der E-Mail'),
        ),
    ]
