# Generated by Django 4.0.3 on 2022-06-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence_tests', '0008_alter_chatinterface_chat_message_outgoing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailitem',
            name='email_content',
            field=models.TextField(null=True, verbose_name='Inhalt'),
        ),
    ]
