# Generated by Django 4.0.3 on 2022-06-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence_tests', '0009_alter_emailitem_email_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailitem',
            name='email_teaser',
            field=models.TextField(null=True, verbose_name='Vorschau'),
        ),
    ]
