# Generated by Django 4.0.3 on 2022-11-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence_tests', '0010_emailitem_email_teaser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencedimension',
            options={'verbose_name': 'Kompetenzdimension', 'verbose_name_plural': 'Kompetenzdimensionen'},
        ),
        migrations.AlterField(
            model_name='chatimpulse',
            name='impulse_text',
            field=models.TextField(blank=True, null=True, verbose_name='Text zum Impuls'),
        ),
        migrations.AlterField(
            model_name='chatinterface',
            name='chat_message_incoming_2',
            field=models.TextField(blank=True, max_length=800, verbose_name='Eingehende Nachricht 2 (optional)'),
        ),
        migrations.AlterField(
            model_name='chatinterface',
            name='chat_message_outgoing',
            field=models.TextField(blank=True, max_length=800, verbose_name='Ausgehende Nachricht (optional)'),
        ),
        migrations.AlterField(
            model_name='choiceitem',
            name='option',
            field=models.TextField(verbose_name='Antwortoption'),
        ),
        migrations.AlterField(
            model_name='competencedimension',
            name='dimension_description',
            field=models.TextField(null=True, verbose_name='Beschreibung der Kompetenzdimension'),
        ),
        migrations.AlterField(
            model_name='emailitem',
            name='email_image_sender',
            field=models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='Bild des Senders'),
        ),
        migrations.AlterField(
            model_name='emailitem',
            name='email_name',
            field=models.CharField(max_length=140, null=True, verbose_name='Kennung der E-Mail'),
        ),
        migrations.AlterField(
            model_name='imageimpulse',
            name='impulse_text',
            field=models.TextField(blank=True, null=True, verbose_name='Text zum Impuls'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='image_description',
            field=models.TextField(blank=True, null=True, verbose_name='Text zur Bild-Datei'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='image_name',
            field=models.CharField(max_length=140, null=True, verbose_name='Kennung des Bildes'),
        ),
        migrations.AlterField(
            model_name='questionitem',
            name='question',
            field=models.TextField(null=True, verbose_name='Text zur Frage'),
        ),
    ]
