# Generated by Django 4.0.3 on 2022-11-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence_tests', '0011_alter_competencedimension_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatinterface',
            name='chat_sender_known',
            field=models.BooleanField(default=False, null=True, verbose_name='Absender bekannt'),
        ),
    ]
