# Generated by Django 4.0.3 on 2024-04-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0008_alter_threatsituation_threat_vector'),
        ('competence_tests', '0012_chatinterface_chat_sender_known'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencetest',
            name='threat_situations',
            field=models.ManyToManyField(to='threats.threatsituation', verbose_name='Zugeordnete Bedrohungssituationen'),
        ),
    ]
