# Generated by Django 4.0.3 on 2024-04-23 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competence_tests', '0013_competencetest_threat_situations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailitem',
            name='email_button_text',
        ),
    ]
