# Generated by Django 4.0.3 on 2024-05-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence_tests', '0016_emailitem_email_is_signed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatinterface',
            name='chat_interface_identificator',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Kennung'),
        ),
        migrations.AddField(
            model_name='emailitem',
            name='email_identificator',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Kennung'),
        ),
        migrations.AddField(
            model_name='imageitem',
            name='image_identificator',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Kennung'),
        ),
    ]
