# Generated by Django 4.0.3 on 2024-05-15 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0009_threatsituation_threat_situation_identificator'),
        ('competence_tests', '0017_chatinterface_chat_interface_identificator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatinterface',
            name='chat_interface_identificator',
        ),
        migrations.RemoveField(
            model_name='emailitem',
            name='email_identificator',
        ),
        migrations.RemoveField(
            model_name='imageitem',
            name='image_identificator',
        ),
        migrations.AddField(
            model_name='chatinterface',
            name='threat_situation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='threats.threatsituation', verbose_name='Zugeordnete Bedrohungssituation'),
        ),
        migrations.AddField(
            model_name='emailitem',
            name='threat_situation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='threats.threatsituation', verbose_name='Zugeordnete Bedrohungssituation'),
        ),
        migrations.AddField(
            model_name='imageitem',
            name='threat_situation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='threats.threatsituation', verbose_name='Zugeordnete Bedrohungssituation'),
        ),
        migrations.AddField(
            model_name='questionitem',
            name='threat_situation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='threats.threatsituation', verbose_name='Zugeordnete Bedrohungssituation'),
        ),
    ]
