# Generated by Django 4.0.3 on 2024-05-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competence_tests', '0021_questionitem_competence_dimension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionitem',
            name='competence_dimension',
        ),
    ]
