# Generated by Django 4.0.3 on 2024-05-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence_tests', '0023_questionitem_competence_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageitem',
            name='impulse_number',
            field=models.CharField(max_length=140, null=True, verbose_name='Nummer des Impulses'),
        ),
    ]
