# Generated by Django 4.0.3 on 2024-05-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence_tests', '0024_imageitem_impulse_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatinterface',
            name='impulse_number',
            field=models.CharField(max_length=140, null=True, verbose_name='Nummer des Impulses'),
        ),
        migrations.AddField(
            model_name='emailitem',
            name='impulse_number',
            field=models.CharField(max_length=140, null=True, verbose_name='Nummer des Impulses'),
        ),
    ]
