# Generated by Django 4.0.3 on 2024-09-27 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competence_tests', '0026_remove_questionitem_question_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageitem',
            name='image_name',
        ),
    ]
