# Generated by Django 4.0.3 on 2022-07-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threats', '0002_alter_threatarea_options_alter_threatevent_options_and_more'),
        ('job_profiles', '0005_alter_jobprofile_job_description'),
        ('competence_tests', '0010_emailitem_email_teaser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=140, verbose_name='Bezeichnung')),
                ('training_description', models.CharField(max_length=800, verbose_name='Beschreibung')),
                ('threat_event', models.ManyToManyField(null=True, to='threats.threatevent', verbose_name='Zugeordnetes Bedrohungsereignis')),
            ],
            options={
                'verbose_name': 'SETA Programm Inhalt',
                'verbose_name_plural': 'SETA Progamm Inhalt',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=140, verbose_name='Bezeichnung')),
                ('training_description', models.CharField(max_length=800, verbose_name='Beschreibung')),
                ('competence_dimension', models.ManyToManyField(null=True, to='competence_tests.competencedimension', verbose_name='Zugeordnete Kompetenzdimensionen')),
                ('job_profile', models.ManyToManyField(null=True, to='job_profiles.jobprofile', verbose_name='Zugeordnete Anforderungsprofile')),
                ('trainings_topic', models.ManyToManyField(to='trainings.trainingscontent', verbose_name='Zugeordnete Trainingsinhalte')),
            ],
            options={
                'verbose_name': 'SETA Programm',
                'verbose_name_plural': 'SETA Programme',
            },
        ),
    ]
