# Generated by Django 4.0.3 on 2022-07-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence_tests', '0010_emailitem_email_teaser'),
        ('job_profiles', '0005_alter_jobprofile_job_description'),
        ('threats', '0005_alter_threatsituation_job_profile'),
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='competence_dimension',
            field=models.ManyToManyField(blank=True, to='competence_tests.competencedimension', verbose_name='Zugeordnete Kompetenzdimensionen'),
        ),
        migrations.AlterField(
            model_name='training',
            name='job_profile',
            field=models.ManyToManyField(blank=True, to='job_profiles.jobprofile', verbose_name='Zugeordnete Anforderungsprofile'),
        ),
        migrations.AlterField(
            model_name='trainingscontent',
            name='threat_event',
            field=models.ManyToManyField(blank=True, to='threats.threatevent', verbose_name='Zugeordnetes Bedrohungsereignis'),
        ),
    ]
