# Generated by Django 4.0.3 on 2022-11-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_alter_training_competence_dimension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_description',
            field=models.TextField(verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='trainingscontent',
            name='training_description',
            field=models.TextField(verbose_name='Beschreibung'),
        ),
    ]
