# Generated by Django 4.0.3 on 2022-11-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_alter_training_training_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='training_description',
        ),
    ]
