# Generated by Django 4.0.3 on 2022-11-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_remove_training_training_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='training_url',
            field=models.URLField(null=True, verbose_name='Link'),
        ),
    ]
