# Generated by Django 4.0.3 on 2022-11-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_training_training_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(max_length=140, verbose_name='Vermittlungsmethode')),
            ],
            options={
                'verbose_name': 'Vermittlungsmethode',
                'verbose_name_plural': 'Vermittlungsmethoden',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=140, verbose_name='Sprache')),
            ],
            options={
                'verbose_name': 'Sprache des Trainings',
                'verbose_name_plural': 'Sprache der Trainings',
            },
        ),
        migrations.CreateModel(
            name='TargetAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_name', models.CharField(max_length=140, verbose_name='Zielgruppenbezeichnung')),
            ],
            options={
                'verbose_name': 'Zielgruppe',
                'verbose_name_plural': 'Zielgruppen',
            },
        ),
        migrations.RemoveField(
            model_name='training',
            name='job_profile',
        ),
        migrations.AddField(
            model_name='training',
            name='certification',
            field=models.IntegerField(choices=[(1, 'Ohne Zertifizierung'), (2, 'Mit Zertifizierung')], default=1, verbose_name='Zertifizierung'),
        ),
        migrations.AddField(
            model_name='training',
            name='costs',
            field=models.IntegerField(choices=[(1, 'Kostenlos'), (2, 'Kostenlos mit zeitlicher Befristung'), (3, 'Zahlungspflichtig')], default=1, verbose_name='Kosten'),
        ),
        migrations.AddField(
            model_name='training',
            name='registration',
            field=models.IntegerField(choices=[(1, 'Ohne Registrierung'), (2, 'Mit Registrierung')], default=1, verbose_name='Registrierung'),
        ),
        migrations.AddField(
            model_name='training',
            name='training_provider',
            field=models.TextField(null=True, verbose_name='Anbieter'),
        ),
        migrations.AddField(
            model_name='training',
            name='delivery_method',
            field=models.ManyToManyField(to='trainings.deliverymethod', verbose_name='Zugeordnete Vermittlungsmethode'),
        ),
        migrations.AddField(
            model_name='training',
            name='language',
            field=models.ManyToManyField(to='trainings.language', verbose_name='Zugeordnete Sprache'),
        ),
        migrations.AddField(
            model_name='training',
            name='target_audience',
            field=models.ManyToManyField(to='trainings.targetaudience', verbose_name='Zugeordnete Zielgruppe'),
        ),
    ]
