# Generated by Django 4.0.3 on 2022-11-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_deliverymethod_language_targetaudience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='trainings_topic',
        ),
    ]
