# Generated by Django 4.0.3 on 2022-11-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0008_alter_training_training_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='certification',
            field=models.IntegerField(choices=[(1, 'Ja'), (2, 'Nein')], default=1, verbose_name='Zertifizierung'),
        ),
        migrations.AlterField(
            model_name='training',
            name='registration',
            field=models.IntegerField(choices=[(1, 'Ja'), (2, 'Nein')], default=1, verbose_name='Registrierung'),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_url',
            field=models.URLField(max_length=400, null=True, verbose_name='Link'),
        ),
    ]
