# Generated by Django 4.0.3 on 2022-11-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_profiles', '0006_jobprofile_job_tasks'),
        ('trainings', '0009_alter_training_certification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='target_audience',
        ),
        migrations.AddField(
            model_name='training',
            name='job_profile',
            field=models.ManyToManyField(to='job_profiles.jobprofile', verbose_name='Zugeordnete Anforderungsprofile'),
        ),
        migrations.DeleteModel(
            name='TargetAudience',
        ),
    ]
