# Generated by Django 4.0.3 on 2022-11-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0010_remove_training_target_audience_training_job_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='job_profile',
        ),
    ]
