# Generated by Django 4.0.3 on 2022-11-30 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0011_remove_training_job_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='competence_dimension',
        ),
    ]
