# Generated by Django 4.0.3 on 2023-10-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence_tests', '0012_chatinterface_chat_sender_known'),
        ('trainings', '0012_remove_training_competence_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='competence_dimension',
            field=models.ManyToManyField(blank=True, to='competence_tests.competencedimension', verbose_name='Zugeordnete Kompetenzdimensionen'),
        ),
        migrations.AddField(
            model_name='training',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Sehr einfach (Grundlagen)'), (2, 'Einfach (für Anfänger)'), (3, 'Schwierig (Erfordert Sicherheits-Vorwissen'), (4, 'Schwierig (Erfordert hohes Sicherheits-Vorwissen')], default=1, verbose_name='Schwierigkeitsgrad'),
        ),
        migrations.AddField(
            model_name='training',
            name='time_invest',
            field=models.IntegerField(choices=[(1, 'Kaum Zeitaufwand'), (2, 'Geringer Zeitaufwand'), (3, 'Hoher Zeitaufwand'), (4, 'Sehr hoher Zeitaufwand')], default=1, verbose_name='Zeitaufwand'),
        ),
        migrations.AddField(
            model_name='training',
            name='trainings_topic',
            field=models.ManyToManyField(to='trainings.trainingscontent', verbose_name='Zugeordnete Trainingsinhalte'),
        ),
    ]
