# Generated by Django 4.0.3 on 2023-10-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0008_alter_threatsituation_threat_vector'),
        ('trainings', '0013_training_competence_dimension_training_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='trainings_topic',
        ),
        migrations.AddField(
            model_name='training',
            name='threat_event',
            field=models.ManyToManyField(blank=True, to='threats.threatevent', verbose_name='Zugeordnetes Bedrohungsereignis'),
        ),
    ]
