# Generated by Django 4.0.3 on 2023-10-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0008_alter_threatsituation_threat_vector'),
        ('trainings', '0014_remove_training_trainings_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='target_group',
            field=models.IntegerField(choices=[(1, 'Generisch'), (2, 'Spezifisch'), (3, 'KMUs'), (4, 'Kliniken'), (4, 'Konsument')], default=1, verbose_name='Zielgruppe'),
        ),
        migrations.AlterField(
            model_name='training',
            name='threat_event',
            field=models.ManyToManyField(blank=True, to='threats.threatevent', verbose_name='Zugeordnete Bedrohungsereignisse'),
        ),
        migrations.DeleteModel(
            name='TrainingsContent',
        ),
    ]
