# Generated by Django 4.0.3 on 2023-10-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0015_training_target_group_alter_training_threat_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_name', models.CharField(max_length=140, verbose_name='Zielgruppenbezeichnung')),
            ],
            options={
                'verbose_name': 'Zielgruppe',
                'verbose_name_plural': 'Zielgruppen',
            },
        ),
        migrations.AlterField(
            model_name='training',
            name='certification',
            field=models.IntegerField(choices=[(1, 'Nein'), (2, 'Ja')], default=1, verbose_name='Zertifizierung'),
        ),
        migrations.RemoveField(
            model_name='training',
            name='target_group',
        ),
        migrations.AddField(
            model_name='training',
            name='target_group',
            field=models.ManyToManyField(to='trainings.targetaudience', verbose_name='Zielgruppe'),
        ),
    ]
