# Generated by Django 4.0.3 on 2023-10-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0016_targetaudience_alter_training_certification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='certification',
            field=models.IntegerField(choices=[(1, 'Ja'), (2, 'Nein')], default=1, verbose_name='Zertifizierung'),
        ),
        migrations.AlterField(
            model_name='training',
            name='registration',
            field=models.IntegerField(choices=[(1, 'Nein'), (2, 'Ja')], default=1, verbose_name='Registrierung'),
        ),
    ]
