# Generated by Django 4.0.3 on 2024-02-11 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0018_traininggroup_remove_training_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='training_group',
        ),
    ]
