# Generated by Django 4.0.3 on 2024-02-11 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0019_remove_training_training_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='training_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.traininggroup', verbose_name='Zugeordnete Trainings-Gruppe'),
        ),
    ]
