# Generated by Django 4.0.3 on 2024-02-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence_tests', '0012_chatinterface_chat_sender_known'),
        ('trainings', '0020_training_training_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='competence_dimension',
            field=models.ManyToManyField(blank=True, related_name='competence_dimensions', to='competence_tests.competencedimension', verbose_name='Zugeordnete Kompetenzdimensionen'),
        ),
    ]
