# Generated by Django 4.0.3 on 2024-02-11 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0021_alter_training_competence_dimension'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='competence_dimension',
            new_name='competence_dimensions',
        ),
    ]
