# Generated by Django 4.0.3 on 2022-06-09 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=140)),
                ('area_description', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=140)),
                ('event_description', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_profile', models.ManyToManyField(to='job_profiles.jobprofile')),
                ('threat_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threats.threatarea')),
                ('threat_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threats.threatevent')),
            ],
        ),
        migrations.CreateModel(
            name='ThreatSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_description', models.CharField(max_length=800)),
                ('threat_vector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threats.threatvector')),
            ],
        ),
    ]
