# Generated by Django 4.0.3 on 2022-06-28 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_profiles', '0004_remove_jobprofile_job_category'),
        ('threats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threatarea',
            options={'verbose_name': 'Bedrohungsbereich', 'verbose_name_plural': 'Bedrohungsbereiche'},
        ),
        migrations.AlterModelOptions(
            name='threatevent',
            options={'verbose_name': 'Bedrohungsereignis', 'verbose_name_plural': 'Bedrohungsereignisse'},
        ),
        migrations.AlterModelOptions(
            name='threatsituation',
            options={'verbose_name': 'Bedrohungssituation', 'verbose_name_plural': 'Bedrohungssituationen'},
        ),
        migrations.AlterModelOptions(
            name='threatvector',
            options={'verbose_name': 'Bedrohungsvektor', 'verbose_name_plural': 'Bedrohungsvektoren'},
        ),
        migrations.AlterField(
            model_name='threatarea',
            name='area_description',
            field=models.CharField(max_length=800, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='threatarea',
            name='area_name',
            field=models.CharField(max_length=140, verbose_name='Bezeichnung'),
        ),
        migrations.AlterField(
            model_name='threatevent',
            name='event_description',
            field=models.CharField(max_length=800, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='threatevent',
            name='event_name',
            field=models.CharField(max_length=140, verbose_name='Bezeichnung'),
        ),
        migrations.AlterField(
            model_name='threatsituation',
            name='threat_description',
            field=models.CharField(max_length=800, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='threatsituation',
            name='threat_vector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threats.threatvector', verbose_name='Zugeordneter Bedrohungsvektor'),
        ),
        migrations.AlterField(
            model_name='threatvector',
            name='job_profile',
            field=models.ManyToManyField(to='job_profiles.jobprofile', verbose_name='Zugeordnete Anforderungsprofile'),
        ),
        migrations.AlterField(
            model_name='threatvector',
            name='threat_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threats.threatarea', verbose_name='Zugeordneter Bedrohungsbereich'),
        ),
        migrations.AlterField(
            model_name='threatvector',
            name='threat_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threats.threatevent', verbose_name='Zugeordnetes Bedrohungsereignis'),
        ),
    ]
