# Generated by Django 4.0.3 on 2022-07-21 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_profiles', '0005_alter_jobprofile_job_description'),
        ('threats', '0003_alter_threatsituation_threat_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threatvector',
            name='job_profile',
        ),
        migrations.AddField(
            model_name='threatsituation',
            name='job_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_profiles.jobprofile', verbose_name='Zugeordnetes Anforderungsprofil'),
        ),
    ]
