# Generated by Django 4.0.3 on 2022-07-21 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_profiles', '0005_alter_jobprofile_job_description'),
        ('threats', '0004_remove_threatvector_job_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatsituation',
            name='job_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_profiles.jobprofile', verbose_name='Zugeordnetes Anforderungsprofil'),
        ),
    ]
