# Generated by Django 4.0.3 on 2022-11-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0005_alter_threatsituation_job_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatarea',
            name='area_description',
            field=models.TextField(null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='threatevent',
            name='event_description',
            field=models.TextField(null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='threatsituation',
            name='threat_description',
            field=models.TextField(null=True, verbose_name='Beschreibung'),
        ),
    ]
