# Generated by Django 4.0.3 on 2022-11-29 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threats', '0007_threatvector_threat_vector_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatsituation',
            name='threat_vector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='threats.threatvector', verbose_name='Zugeordneter Bedrohungsvektor'),
        ),
    ]
