# Generated by Django 4.0.3 on 2022-06-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobprofile',
            options={'ordering': ['job_name'], 'verbose_name': 'Anforderungsprofil', 'verbose_name_plural': 'Anforderungsprofile'},
        ),
        migrations.RemoveField(
            model_name='jobprofile',
            name='job_category',
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='job_description',
            field=models.CharField(max_length=140, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='job_name',
            field=models.CharField(max_length=140, verbose_name='Bezeichnung'),
        ),
    ]
