# Generated by Django 4.0.3 on 2022-06-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_profiles', '0002_alter_jobprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='job_category',
            field=models.CharField(blank=True, max_length=140, verbose_name='Kategorie'),
        ),
    ]
