# Generated by Django 4.0.3 on 2022-11-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_profiles', '0006_jobprofile_job_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='show_job_profile',
            field=models.BooleanField(default=False, verbose_name='Anzeigen'),
        ),
    ]
