# Generated by Django 4.0.3 on 2024-04-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_profiles', '0007_jobprofile_show_job_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofile',
            name='job_tasks',
            field=models.TextField(null=True, verbose_name='Tätigkeiten'),
        ),
    ]
